version: "3"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx4096m"
    networks:
    - efk-idranalysis
    volumes:
    - ./volumes/es:/usr/share/elasticsearch/data

  fluentd:
    build: ./fluentd
    networks:
    - efk-idranalysis
    volumes:
    - ./fluentd/:/fluentd/etc/:ro
    - ./volumes/fluentd/:/fluentd/pos/
    - ./haproxy:/idranalysis-haproxy-logs:ro

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.0
    networks:
    - efk-idranalysis

  nginx:
    image: library/nginx:1.15.5
    networks:
    - efk-idranalysis
    ports:
    - "12381:8080"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/passwd:/etc/nginx/passwd:ro

networks:
  efk-idranalysis:

#volumes:
